### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by ondras76** [radimkeseg/NeoPixel-Nudge#1]
Hello, can you help me please with this issue? During the compiling I see this error message.

In file included from C:\Users\xxx\Documents\Arduino\sketch_jun13a\sketch_jun13a.ino:36:
c:\Users\xxx\Documents\Arduino\libraries\NeoPixel-Nudge-main/embHTML.h:20:12: error: redefinition of 'const char PAGE_INDEX []'
   20 | const char PAGE_INDEX[] PROGMEM = R"=====(
      |            ^~~~~~~~~~
In file included from C:\........\Documents\Arduino\sketch_jun13a\sketch_jun13a.ino:17:
c:\....\Documents\Arduino\libraries\NeoPixel-Nudge-main/embHTML.h:20:12: note: 'const char PAGE_INDEX [7974]' previously defined here
   20 | const char PAGE_INDEX[] PROGMEM = R"=====(
      |            ^~~~~~~~~~

exit status 1

Compilation error: exit status 1

Thank you for your help!

**Comment by radimkeseg** [comment]
Hi @ondras76 
well, I guess it is an issue with multiple definitions of the same; the only thing that happens is that it places the code in FLASH see https://www.arduino.cc/reference/en/language/variables/utilities/progmem/ . So feel free to use any other char* variable, readjust the code there where it references it, and you should be able to move forward.
Regards,
R.

**Comment by ondras76** [comment]
Thank you,I was finish the project in esphome, is much more easy for me.Ondrej.3. 7. 2023 v 16:31, Radim Keseg ***@***.***>:﻿
Hi @ondras76
well, I guess it is an issue with multiple definitions of the same; the only thing that happens is that it places the code in FLASH see https://www.arduino.cc/reference/en/language/variables/utilities/progmem/ . So feel free to use any other char* variable, readjust the code there where it references it, and you should be able to move forward.
Regards,
R.
